### ISSUE TITLE
No module named 'hole_filling_liepa.core'

### ISSUE THREAD

**Issue by youssef962** [russelmann/hole-filling-liepa#1]
I tried to run this code on jupyter and it gave me the shown error.

**Comment by russelmann** [comment]
Did you follow the installation steps error-free? What is your OS and Python version?
Note that if you have a compatible configuration you can use PyPI installation.

**Comment by russelmann** [comment]
@youssef962 a quick update: now conda installation is available.

**Comment by MaksymTymkovych** [comment]
Seems error is still present. 
I installed package via conda.
I got the same error.

To work with library I did the following:

```
import hole_filling_liepa.native
from hole_filling_liepa.utils import read_obj, write_obj
vertices, faces = read_obj('data/bunny-1.obj')
boundary_loops = hole_filling_liepa.native.find_boundary_loops(faces)
patch_faces = hole_filling_liepa.native.fill_hole_liepa(vertices, faces, boundary_loops[0], method='angle')
write_obj('output.obj', vertices, patch_faces)
```

**Comment by russelmann** [comment]
Could you provide more information? Version of python, OS, full error output.

**Comment by MaksymTymkovych** [comment]
I found the reason. 
We should run test script outside of original git folder. Because there is mismatching between scripts & locations.

**Comment by russelmann** [comment]
In case you are using conda installation, local (clone) git folder is not used. Package is installed from conda forge online repo into your python environment. I am not sure which mismatch do you mean?

**Comment by MaksymTymkovych** [comment]
Yes, you are right. 
I made clone of your repository, to test algorithm on your data. And run test script in that git folder.
And that was my mistake, because in that case script search library in the active folder (clonned directory) not in the anaconda environment.

**Comment by russelmann** [comment]
Got it, thanks for the clarification. I'm closing this issue.
